controller_manager_ns: ''
  controller_list:
    - name: kuka_gripper/KUKA
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - iiwa14_joint_1
        - iiwa14_joint_2
        - iiwa14_joint_3
        - iiwa14_joint_4
        - iiwa14_joint_5
        - iiwa14_joint_6
        - iiwa14_joint_7
    - name: kuka_gripper/gripper
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - gripper_finger1_joint
