controller_list:
  - name: fake_gripper_controller
    joints:
      - gripper_finger1_joint
  - name: fake_KUKA_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7